### ISSUE TITLE
VEVO plugin fails to load

### ISSUE THREAD

**Issue by spike411** [learningit/plugin.video.myvevo#2]
It seems like the VEVO add-on does not work in some regions where the VEVO service is not available.
Some users seem to be confused by this.
Perhaps the add-on could detect this situation and show some helpful information message (saying that the add-on does not work due to region restrictions on the side of VEVO?)

This is the relevant part of the kodi.log file:
```
13:07:46 T:10264   ERROR: XFILE::CDirectory::GetDirectory - Error getting
13:07:46 T:7080   ERROR: Previous line repeats 1 times.
13:07:46 T:7080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\Spike\AppData\Roaming\Kodi\addons\plugin.video.myvevo\default.py", line 540, in <module>
                                                if mode==  None:  getSources()
                                              File "C:\Users\Spike\AppData\Roaming\Kodi\addons\plugin.video.myvevo\default.py", line 138, in getSources
                                                a = getBase()
                                              File "C:\Users\Spike\AppData\Roaming\Kodi\addons\plugin.video.myvevo\default.py", line 129, in getBase
                                                blob = re.compile('config:(.+?)cdn:').search(html).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
13:07:46 T:4568   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.myvevo/
13:07:46 T:4568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.myvevo/) failed
```

Tested on stable LibreELEC v7.0.2 (x86_64), Alpha Kodi 17.0 on Windows 10…

**Comment by spike411** [comment]
The add-on installed through Kodi 17.0-alpha3 (win32) is 2.0.12.
But I can see there is version 3.0.4 in your git repository.

So – what is the correct version?
Is 3.0.x still under development, so it’s not in the official Team Kodi repository?
